### ISSUE TITLE
Wrapper dll code ???

### ISSUE THREAD

**Issue by ZAMA30** [HapticPlugin/HPGE-wrappers#2]
I have to implmente the  posibility of using collsion detection with unity anf set force and torque for a procedurall mesh .
If it is possible to have code of the wrapper. 
Thank you so much for your plugin

**Comment by nico202** [comment]
Here you go!
https://github.com/HapticPlugin/chai3d-with-HPGE

Please, if you try, give me feedback about the build instructions! Also, PR are welcome :)
