### ISSUE TITLE
code for dll file

### ISSUE THREAD

**Issue by HanRWTH** [HapticPlugin/HPGE-wrappers#3]
I would like to add some functions to compute feedback force. 
If it is possible to have code of the wrapper? 
Thank you so much!

**Comment by nico202** [comment]
Sorry for the late reply! See [here!](https://github.com/HapticPlugin/HPGE-wrappers/issues/4#issuecomment-1396834523)

**Comment by HapticPlugin** [comment]
Here you go!
https://github.com/HapticPlugin/chai3d-with-HPGE

Please, if you try, give me feedback about the build instructions! Also, PR are welcome :)
